name: Node.js CI

on:
  push:
    branches: ["master", "Fong"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4

      - name: Docker Build with ENV
        run: |
          echo "API_URL=${{ secrets.API_URL }}" > .env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env

          docker compose up -d --build --force-recreate
